/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthResetPasswordImport } from './routes/auth/reset-password'
import { Route as AuthRecoverPasswordImport } from './routes/auth/recover-password'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as LayoutSettingsIndexImport } from './routes/_layout/settings/index'
import { Route as LayoutItemsIndexImport } from './routes/_layout/items/index'
import { Route as LayoutAdminIndexImport } from './routes/_layout/admin/index'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  path: '/auth/signup',
  getParentRoute: () => rootRoute,
} as any)

const AuthResetPasswordRoute = AuthResetPasswordImport.update({
  path: '/auth/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const AuthRecoverPasswordRoute = AuthRecoverPasswordImport.update({
  path: '/auth/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutSettingsIndexRoute = LayoutSettingsIndexImport.update({
  path: '/settings/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutItemsIndexRoute = LayoutItemsIndexImport.update({
  path: '/items/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminIndexRoute = LayoutAdminIndexImport.update({
  path: '/admin/',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/recover-password': {
      preLoaderRoute: typeof AuthRecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/auth/reset-password': {
      preLoaderRoute: typeof AuthResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/auth/signup': {
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/admin/': {
      preLoaderRoute: typeof LayoutAdminIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/items/': {
      preLoaderRoute: typeof LayoutItemsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings/': {
      preLoaderRoute: typeof LayoutSettingsIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutIndexRoute,
    LayoutAdminIndexRoute,
    LayoutItemsIndexRoute,
    LayoutSettingsIndexRoute,
  ]),
  AboutRoute,
  AuthLoginRoute,
  AuthRecoverPasswordRoute,
  AuthResetPasswordRoute,
  AuthSignupRoute,
])

/* prettier-ignore-end */
